source "http://rubygems.org"

# Specify your gem's dependencies in frank-cucumber.gemspec
gemspec

gem 'sim-launcher', :git => 'https://github.com/rhgills/Sim-Launcher', :branch => 'launch-app-retina', :submodules => true